apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats {
        port => 5044
      }
      udp {
        port => 5044
        codec => "json"
        buffer_size => "1048576"
      }
      tcp {
        port  => 5044
        codec => "json"
      }
    }
    filter {
       grok {
          match => { "message" => "%{DATA}json\(%{DATA:message}\)json%{DATA}" }
          overwrite => [ "message" ]
       }
       json {
          source => "message"
       }
    }
    output {
      elasticsearch {
        index => "logstash-%{[@metadata][beat]}"
        hosts => [ "${ES_HOSTS}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        cacert => '/etc/logstash/certificates/ca.crt'
      }
    }
