apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    app: cerebro
spec:
  selector:
    app: cerebro
  ports:
    - port: 9000
      name: http
{{- if not .Values.ingressEnabled }}
  type: NodePort
{{- end -}}
