apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
  - port: 5601
{{- if not .Values.ingressEnabled }}
  type: NodePort
{{- end }}
  selector:
    app: kibana
