apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kibana
                operator: In
                values:
                - "true"
      containers:
      - name: kibana
        {{- if .Values.defaultImage }}
        image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2-amd64
        {{- else }}
        image: "{{ .Values.kibanaImage }}:{{ .Values.kibanaImageTag }}"
        {{- end }}
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          {{- if .Values.securityEnabled }}
          - name: ELASTICSEARCH_USERNAME
            value: "kibana"
          - name: ELASTICSEARCH_PASSWORD
            value: "{{ .Values.password_kibana }}"
          {{- end }}
          {{- if .Values.ingressEnabled }}
          - name: SERVER_BASEPATH
            value: /kibana
          {{- end }}
        ports:
        - containerPort: 5601
