{{- if .Values.securityEnabled }}
apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch-security
  labels:
    app: elasticsearch
spec:
  serviceAccountName: k8s-role
  containers:
  - name: elasticsearch-security
    imagePullPolicy: IfNotPresent
    image: msplva-dsnsmt71.csc.nycnet:5000/dsny/elasticsearch-passwordsetter:7.5.2
  restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-role1
subjects:
- kind: ServiceAccount
  name: k8s-role
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-role
{{- end }}
