{{- if .Values.ingressEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: efk-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    {{- if .Values.ingressTls }}
    ingress.kubernetes.io/secure-backends: "true"
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /cerebro(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: cerebro
            port: 
              number: 9000
  - http:
      paths:
      - path: /kibana(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: kibana
            port: 
              number: 5601
{{- if .Values.ingressTls }}
  tls:
  - secretName: {{ .Values.ingressCertname }}
{{- end }}
{{- end }}
